<?php

/**
 * @file
 * Preprocess functions for Environmental Health & Safety.
 */

/**
 * Prepares variables for the html.html.twig template.
 */
function ehs_subtheme_preprocess_html(&$variables) {
  $variables['stanford_basic_path'] = \Drupal::service('extension.list.theme')->getPath('stanford_basic');
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function ehs_subtheme_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  if (!empty($variables['elements']['#id']) && $variables['elements']['#id'] == 'ehs_subtheme_search') {
    $suggestions[] = 'block__stanford_basic_search';
  }
}
